lms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("univ_app.urls")),
]

univ_app/models.py
import os
from itertools import chain

from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


class Subject(models.Model):
    title = models.CharField(max_length=200, default="", blank=True)
    description = models.TextField(default="", blank=True)
    image = models.ImageField(
        upload_to="uploads/subjects/", blank=True, null=True, default="test.png"
    )
    teacher = models.ForeignKey(
        "Teacher", blank=True, null=True, on_delete=models.SET_NULL
    )
    st_group = models.ForeignKey(
        "StGroup", blank=True, null=True, on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.title

    @property
    def all_tasks(self):
        common_tasks = self.commontask_set.all()
        info_tasks = self.infotask_set.all()
        test_tasks = self.test_set.all()
        tasks = list(chain(common_tasks, info_tasks, test_tasks))
        tasks.sort(key=lambda task: task.created_at)
        return tasks


class Document(models.Model):
    title = models.CharField(max_length=200, default="", blank=True)
    subject = models.ForeignKey(
        "Subject", blank=True, null=True, on_delete=models.SET_NULL
    )
    student = models.ForeignKey(
        "Student", blank=True, null=True, on_delete=models.SET_NULL
    )
    doc = models.FileField(upload_to="uploads/documents/", null=True)

    @property
    def filename(self):
        return os.path.basename(self.doc.name)


class StGroup(models.Model):
    title = models.CharField(max_length=200, default="", blank=True)

    def __str__(self):
        return self.title


class Student(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    st_group = models.ForeignKey(
        "StGroup", blank=True, null=True, on_delete=models.SET_NULL
    )
    profile_picture = models.ImageField(
        upload_to="uploads/profile_pictures/%Y/", default="student.jpg", null=True
    )

    def __str__(self):
        return self.user.first_name

    def get_all_tasks_by_type(self, some_type):
        ans_common_tasks = AnsweredCommonTask.objects.filter(
            student=self, status=some_type
        )
        taken_tests = TakenTest.objects.filter(student=self, status=some_type)
        info_tasks = AnsweredInfoTask.objects.filter(student=self, status=some_type)
        tasks = list(chain(ans_common_tasks, taken_tests, info_tasks))
        return tasks


class Teacher(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)
    profile_picture = models.ImageField(
        upload_to="uploads/profile_pictures/%Y/", default="teacher.jpg", null=True
    )

    def __str__(self):
        return self.user.first_name


class Task(models.Model):
    # this field is present in Test itself
    title = models.CharField(max_length=200, default="", blank=True)
    # this field is present in Test itself
    description = models.TextField(default="", blank=True)
    subject = models.ForeignKey(
        "Subject", blank=True, null=True, on_delete=models.SET_NULL
    )
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    created_by = models.ForeignKey(
        "Teacher", blank=True, null=True, on_delete=models.SET_NULL
    )

    class Meta:
        abstract = True

    def get_type(self):
        return str(self.__class__.__name__)

    def get_type_for_user(self):
        type_name = self.get_type()
        if type_name == "CommonTask":
            return "General-purpose task"
        if type_name == "Test":
            return "Test"
        if type_name == "InfoTask":
            return "Materials"


class CommonTask(Task):
    file = models.FileField(upload_to="uploads/common_tasks/", blank=True, null=True)

    def __str__(self):
        return self.title


class Test(Task):
    slug = models.SlugField(max_length=120, blank=True, null=True)
    link = models.CharField(max_length=1000, default="")
    image = models.ImageField(
        upload_to="uploads/", blank=True, null=True, default="test.png"
    )

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.title) + "-" + str(self.id)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f"/articles/{self.slug}/"


class InfoTask(Task):
    file = models.FileField(upload_to="uploads/info_tasks/", blank=True, null=True)

    def __str__(self):
        return self.title


class AnsweredTask(models.Model):
    ASSIGNED = "ASSIGNED"
    DONE = "DONE"
    PASSED = "PASSED"
    EVALUATED = "EVALUATED"
    CHECKED = "CHECKED"  # for InfoTask

    STATUS_CHOICES = (
        (ASSIGNED, "Assigned"),
        (DONE, "Done"),
        (PASSED, "Passed"),
        (EVALUATED, "Evaluated"),
        (CHECKED, "CHECKED"),
    )

    student = models.ForeignKey(
        "Student", blank=True, null=True, on_delete=models.SET_NULL
    )
    finished_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    status = models.CharField(
        max_length=255, choices=STATUS_CHOICES, default=ASSIGNED, blank=True
    )

    class Meta:
        abstract = True

    def related_task(self):
        class_name = self.__class__.__name__
        match class_name:
            case "AnsweredCommonTask":
                return self.common_task  # pylint: disable=no-member
            case "TakenTest":
                return self.related_test  # pylint: disable=no-member
            case "AnsweredInfoTask":
                return self.related_info_task  # pylint: disable=no-member


class AnsweredCommonTask(AnsweredTask):
    grade = models.IntegerField(null=True, blank=True)
    answer = models.TextField(null=True, default="")
    file = models.FileField(
        upload_to="uploads/answered_common_tasks/", blank=True, null=True
    )
    common_task = models.ForeignKey(
        "CommonTask", blank=True, null=True, on_delete=models.CASCADE
    )
    comment_from_teacher = models.TextField(default="", blank=True)

    def __str__(self):
        return str(self.common_task)


class AnsweredInfoTask(AnsweredTask):
    related_info_task = models.ForeignKey(
        "InfoTask", blank=True, null=True, on_delete=models.CASCADE
    )


class TakenTest(AnsweredTask):
    grade = models.IntegerField(null=True, blank=True)
    related_test = models.ForeignKey("Test", on_delete=models.CASCADE, null=True)
    score = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.related_test)

    class Meta:
        unique_together = (("student", "related_test"),)


class Question(models.Model):
    question = models.TextField(default="")
    answered_correctly = models.BooleanField(default=False)
    related_test = models.ForeignKey("Test", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.question

    def get_test_questions(test: Test):
        questions = Question.objects.filter(related_test=test)
        return questions


class Answer(models.Model):
    answer = models.CharField(max_length=1000)
    was_chosen = models.BooleanField(default=False)
    is_right = models.BooleanField(default=False)
    related_question = models.ForeignKey(
        "Question", on_delete=models.CASCADE, null=True
    )

    def get_answers(question: Question):
        answers = Answer.objects.filter(related_question=question)
        return answers

    def __repr__(self):
        return self.answer

    def __str__(self):
        return self.answer


class AnsweredQuestion(models.Model):
    related_taken_test = models.ForeignKey(
        "TakenTest", on_delete=models.CASCADE, null=True
    )
    related_question = models.ForeignKey(
        "Question", on_delete=models.CASCADE, null=True
    )
    correct = models.BooleanField(default=False)


class GivenAnswer(models.Model):
    related_answered_question = models.ForeignKey(
        "AnsweredQuestion", on_delete=models.CASCADE, null=True
    )
    checked = models.BooleanField(default=False)

univ_app/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import *


class GivenAnswerForm(forms.ModelForm):
    class Meta:
        model = GivenAnswer
        fields = ("checked",)
        labels = {"checked": " "}


class AnswerFormNotModel(forms.Form):
    answer = forms.CharField(max_length=200, widget=forms.Textarea, label="Answer")
    is_right = forms.BooleanField(required=False, label="is correct")

    is_right.widget.attrs.update({"value": "1", "placeholder": "is correct"})
    answer.widget.attrs.update({"cols": "90", "rows": "1", "placeholder": "answer"})


class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = [
            "title",
            "description",
            "image",
        ]

        labels = {
            "title": "Title of the test",
            "description": "Description",
            "image": "Picture",
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = [
            "question",
        ]

        labels = {
            "question": "question",
        }


class AnswerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["answer"].widget.attrs.update(
            {
                "class": "form-control",
                "style": ' placeholder : "Question"; width:700px; height:25px;  display:inline-block;',  # pylint: disable=line-too-long
            }
        )
        self.fields["is_right"].widget.attrs.update(
            {"class": "form-check-input", "style": " display:inline-block;"}
        )

    class Meta:
        model = Answer
        fields = [
            "answer",
            "is_right",
        ]

        labels = {
            "is_right": "Answer is correct",
            "answer": "Answer",
        }


class UserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update(
            {
                "class": "form-control",
                "style": ' placeholder : "Login"',
            }
        )
        self.fields["password"].widget.attrs.update(
            {
                "class": "form-control",
                "style": ' placeholder : "Password"',
            }
        )

    class Meta:
        model = User
        fields = [
            "username",
            "password",
        ]
        labels = {"username": "login", "password": "password"}
        help_texts = {"username": " "}

        widgets = {"password": forms.PasswordInput(attrs={"class": "form-control"})}


class CommonTaskForm(forms.ModelForm):
    class Meta:
        model = CommonTask
        fields = ["title", "description", "file"]
        labels = {
            "title": "Title",
            "description": "Description",
        }

    def __init__(self, *args, **kwargs):
        super(CommonTaskForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs.update({"class": "form-control"})


class InfoTaskForm(forms.ModelForm):
    class Meta:
        model = InfoTask
        fields = ["title", "description", "file"]
        labels = {
            "title": "Title",
            "description": "Description",
        }

    def __init__(self, *args, **kwargs):
        super(InfoTaskForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs.update({"class": "form-control"})


class AnsweredCommonTaskForm(forms.ModelForm):
    class Meta:
        model = AnsweredCommonTask
        fields = ["answer", "file"]
        labels = {
            "description": "Description",
            "file": "Add a document",
        }

    def __init__(self, *args, **kwargs):
        super(AnsweredCommonTaskForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs.update({"class": "form-control"})


class PictureForm(forms.Form):
    field_name = forms.ImageField(required=False)


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ["doc"]
        labels = {
            "doc": "Choose a document to upload",
        }

    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs.update({"class": "form-control"})

templates/tester/create_test/cant_create_test.html
{% extends "tester_base.html" %}

{%block cant_create_test%}
<br>
<div class = "text-wrapper centrate cent" >
  Can't create a test without questions.
  <a href = "{% url 'create_test' subject_id %}" class = "text-warning">Recreate</a>.
</div>

<style>
  .centrate {
    font-size:30px;
    margin:auto;
    color: white;
  }

  .cent{
    margin-left: 25%;
    margin-top: 15%;
    display:float;
  }
</style>
{%endblock%}

templates/tester/create_test/create_questions.html
{% extends "tester_base_with_sidebar.html" %}
{% load static %}

{% block questions_form %}

   <form class = "white_text" action = "#" method="POST"> {% csrf_token %}
       <div class="form-group testformtxt mb-1">
           <textarea class ="form-control"  name="question" cols="40" rows="10" required="" id="id_question" placeholder = "Question text"></textarea>
       </div>

      <div class="form-group ans_group" >
        <button type = "button" class="btn btn-primary plusBtn" name="button"> Add another answer </button>
        <button type="submit" class="btn btn-success btn-md createQuestionButton">Save the question</button>

              <div id = "empty_form" class = "empty_form" >
                {{answer_form_not_model.as_p}}
              </div>

              <div class="empty_form ">
                <p>
                  <label for="id_answer">Answer:</label>
                  <textarea type="text" name="answer" maxlength="200" cols = "90" rows = '1' placeholder="Answer" required="" id="id_answer"></textarea>
                </p>

                <p>
                  <label for="id_is_right">Is correct:</label>
                  <input type="checkbox" name="is_right" id="id_is_right" value = "2">
                </p>
              </div>

         </div>

     </form>

     <form action="{% url 'finish_test_creation' testid %}">
       <button class = "btn btn-danger btn-lg ready_btn" type="submit" name="button">Test is ready</button>
     </form>


    <script defer>

      let num = 3
      const plusBtn = document.querySelector('.plusBtn')
      plusBtn.addEventListener('click', function handler() {
        const emptyForm = document.querySelector('#empty_form')
        let newForm = emptyForm.cloneNode(true)
        newForm.setAttribute("id", ``)

        console.log(newForm)
        console.log(newForm.lastElementChild)
        console.log(newForm.lastElementChild.lastElementChild)

        let checkbox = newForm.lastElementChild.lastElementChild
        checkbox.setAttribute("id", "")
        checkbox.setAttribute("value", `${num}`)
        checkbox.checked = false

        let textarea = newForm.firstElementChild.lastElementChild
        textarea.value = ""

        console.log(newForm.lastElementChild.lastElementChild)

        num += 1
        const ansGroup = document.querySelector(".ans_group")

        ansGroup.appendChild(newForm)
      });
    </script>

<style>

        .ready_btn{
          display: inline;
          float:right;
          margin:50px;
          margin-top: 5px;

        }

        .white_text{
          color:white;
        }

        .plusBtn{
          margin:10px;
          margin-top:20px;
          margin-bottom: 20px;
          margin-left:7%;
          display: inline;
        }

        .ans_group{
        //border: 3px solid red;
        margin: 5px;
        margin-left:30%;
        }

        .hidden{
          display:none
        }

        #empty_form{

        }


        .testformstr{
        margin-top: 50px;
        width:300px;
        margin-left: 500px;
        }

        .testformtxt{
        margin-top: 30px;
        width:700px;
        margin-left: 500px;

        }

        .questionform_importance
        {
        display: inline-block;
        margin-left: 700px;
        width:100px;
        margin: 0px;
        }


        .createQuestionButton{
        margin-top: 20px;
        margin-bottom: 20px;
        margin-left: 300px;
        display:inline;
        }

        .textstyle{
        color:white;
        margin-top: 30px;
        font-size: 22px;
        }

        .finish{
          position: fixed;
          right: 450px;
          bottom: 100px;
          background-color: red;
        }
</style>

{% endblock %}

{% block answer%}
{% for question in previous_questions %}

<br>
<em>{{question}}</em>
<br>

{% endfor %}
{% endblock%}

templates/tester/create_test/create_test.html
{% extends 'tester_base_with_sidebar.html' %}

{% block show_test_form %}

<form action="#" method="POST" enctype="multipart/form-data"> {% csrf_token %}

    <div class="form-group testformstr">
        <input type="text" class="form-control" aria-describedby="emailHelp" placeholder="Test's title" name="title"
               maxlength="100" required="" id="id_title">
    </div>

    <div class="form-group testformtxt">
        <div>
            <textarea class="form-control" name="description" cols="40" rows="10" id="id_description"
                      placeholder="Test's description"></textarea>
            <button type="submit" class="btn btn-success btn-md createTestButton"> Continue</button>
        </div>
    </div>

    <div class="form-group marg">
      <label for="id_image">Add a picture:</label>
      <input type="file" name="image" accept="image/*" id="id_image">
    </div>

</form>

<style >
  .marg{
    margin-left: 40%;
    margin-top:10px;
    color:white;
  }
</style>

<style>
        .testformstr{
        margin-top: 50px;
        width:700px;
        margin-left: 500px;
        }

        .testformtxt{
        margin-top: 10px;
        width:700px;
        margin-left: 500px;
        }

        .createTestButton{
        margin: 10px;
        float:right;
        }

</style>

{% endblock %}